//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        public long Identifiant { get; set; }
        public string RaisonSociale { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string NumeroSiret { get; set; }
        public long IdentifiantAdresse { get; set; }
    
        public virtual Adresse Adresse { get; set; }

        public override string ToString()
        {
            return this.RaisonSociale;
        }
    }
}
